server:
  port: 8887

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    call-setters-on-nulls: true

logging:
  file:
    name: logs/community.log
  level:
    root: info
    com:
      demo:
        community:
#          mapper: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7

mybatis-plus:
  global-config:
    db-config:
#        logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    关闭自动驼峰转换
    mapUnderscoreToCamelCase: false


